### ISSUE TITLE
Better Tooltips

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#16]
### Tasks

- [ ] Simplify hover tooltips for Histogram
- [ ] Add Tooltip for PieChart
- [ ] Allow onClick functionality for all hover interactions
- [ ] Create modal for onClick event listing cast within the data set
