### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#21]
### Tasks

- [x] Create navbar drawer that resizes
- [x] Adjust noms page graphs (maybe tabs)?
- [x] Adjust movie details page graphs
