### ISSUE TITLE
Migrate client to separate folder

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#24]
### Issue Summary
Currently, the frontend is being served from the static directory in ~/api. While this was fine to get the project up and running quickly, this is not viable to grow the project further. I would like to migrate all frontend code in ~/api/static out of the ~/api directory and into a newly created ~/client directory. Here I want to keep the folder structure for now (structure can be tackled in a separate ticket). After the client directory is setup, I want to configure the project with Vite and the final build from ```npm run buld``` to live inside ~/api/build. After this is configured, we can delete the static and template folders from the /api directory. Lastly, the main catch all route in /api/app.py will then need to point to the main html page in the newly created build directory.

## Tasks
- [ ]  Create client directory in root
- [ ] Configure new React project with Vite
- [ ] Move all css and js from ~/api/static to ~/client
- [ ] Configure ```npm run build``` to be created in ~/api/build
- [ ] Route catch_all route to render main html page in build folder
- [ ] Add ~/api/build folder to .gitignore
