### ISSUE TITLE
Cast Member Page

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#27]
### Issue Summary
Create a page for each unique cast member. Use the below layout as inspiration but use the color scheme and theme of Demographix. Feel free to create additional components if need be but stay DRY:

![Screenshot 2023-06-26 175303](https://github.com/mithintv/demographix/assets/13951154/6f7580d4-aad8-4fc9-bdb1-9fee86e11577)

### Tasks
- [ ] Each cast member should have a page with a unique route under /cast/<:cast_member_id>
- [ ] Each unique page should display a photo, name, age, gender, ethnicity, race, and place of birth information (use dummy information until backend route is completed)
- [ ] Each unique cast_member page should display recent movies that the cast member was involved in 
- [ ] Each movie should link to their respective movie page
