### ISSUE TITLE
Cast Member Page Route

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#28]
### Issue Summary
Create unique route for cast members and return appropriate information.

### Tasks
- [ ] Routes should be a GET request that queries for a cast member's information and returns a JSON object
- [ ] JSON object should include id, imdb_id, name, gender_id, gender_name, birthday, deathday, biography, country_of_birth_id, country_of_birth_name, profile_path (img url), list of also_known_as, list of credits, list of ethnicities, and list of races
- [ ] Each element in list of credits should include respective movie information
- [ ] Each element in list of ethnicities should include ethnicity_source_link
- [ ] Each element in list of races should include race_source_link

**Comment by ericlwong** [comment]
@mithintv I can take this on. Please assign to me when you get the chance!
