### ISSUE TITLE
Merge Flask Migrations

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#39]
#### Tasks
- [ ] Copy db schema to schema.sql
- [ ] Drop db in dev env
- [ ] Create db in dev env
- [ ] Delete migrations folder
- [ ] Run `flask db init`
- [ ] Run `psql -d demographix -f schema.sql`
- [ ] Run `flask db migrate -m "Initial migration`
- [ ] Run `flask db upgrade`
