### ISSUE TITLE
Landing Page Summary

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#5]
### Tasks
- [x] Create a summary of movie demographics on a yearly basis based on oscar nominations
- [x] Create dropdown to navigate years
- [x] Create dropdown to summarize multiple years (last 5 years, last 10 years)
- [x] Create logic to summarize multiple years (last 5 years, last 10 years)
