### ISSUE TITLE
Style graphs

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#6]
### Tasks

- [x] Re-style gender pie chart with complementary colors
- [x] Add percentages to gender pie chart
- [x] Re-style age histogram with complementary colors
- [x] Re-style bar chart with complementary colors
