### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by mithintv** [mithintv/demographix#8]
### Tasks

- [x] Create modal for search page
- [x] Add additional queries in addition to search keywords
- [x] Refresh query results when a movie does not exist in the database
